### ISSUE TITLE
Számológép béta teszt

### ISSUE THREAD

**Issue by dobiantal** [dobiantal/AFP_project#13]
Sziasztok! 
Lebuildeltem a kész produkciót meg tudjátok nézni, illetve próbálgassátok nyomkodjátok meg jól működik-e. Az Enter billentyűre működik az egyenlőség operátor, valamint a számok a billentyűzeten szintén. A többi aritmetikai operátorra kattintani kell. Esetleg egy használati utasítást készíthetünk még holnap benn az órán hozzá.
Üdv Anti!

**Comment by FireWolfy89** [comment]
Szia Anti!

Szuperül működnek a funkciók. Annyi észrevételem van, hogy amikor nullával való szorzást választom, nem kapok error üzenetet, csak simán nem végzi el a műveletet. A szorzás logikában raiseltem egy ValueErrort, akkor ez ebben az esetben nem működik? Vagy ezt a frontenden kellene hozzáadni?

**Comment by FireWolfy89** [comment]
Értem, holnap kiegészítjük óra elején.
