### ISSUE TITLE
Python_beállítások

### ISSUE THREAD

**Issue by Patrik960624** [dobiantal/AFP_project#3]
![Python_beállítások](https://github.com/dobiantal/AFP_project/assets/150531017/2f7002d9-e997-4fae-8dfa-14e4d302db45)

Szia!

Segítségedet kérném, majd miket érdemes beállítani pythonban, ami hasznos lesz a projektünknél.

Köszönöm!

**Comment by dobiantal** [comment]
Kedves Patrik!
Ezen a ponton megfelelően választottad az új Virtuális környezet generálását. A Location-t és a Base interpretert alapértelmezetten kell hagyni és a Checkbox-ból a pipát ki lehet venni, hogy készítsen a projecthez main.py-t. Illetve a többi pipálható komponensre sem lesz szükségünk.
Üdvözlettel! Anti

**Comment by Patrik960624** [comment]
Köszönöm! :)
