### ISSUE TITLE
VSCode Pycharm helyett? 

### ISSUE THREAD

**Issue by FireWolfy89** [dobiantal/AFP_project#8]
Szia Antal, 

Egy olyan kérdésem lenne, hogy tudnék Visual Studio Code-ot használni Pycharm helyett, vagy mindenképpen az utóbbira lesz szükség? Már elkezdtem a munkát Pycharm-ban, viszont VSCode-ban kényelmesebb lenne a fejlesztés. 

Üdv:
Máté

**Comment by dobiantal** [comment]
Szia Máté!
Nyugodtan használj VSCode-ot. Bármit ami szimpatikus.
